#!/bin/bash

# Create a simple 180x180 PNG (dark blue with white text "CRM")
# Using base64 encoded minimal PNG
echo "Creating placeholder icons..."

# Create a simple colored square PNG using printf (minimal valid PNG)
# This creates a 1x1 dark blue pixel and we'll just copy it
base64 -d > apple-touch-icon.png << 'EOF'
iVBORw0KGgoAAAANSUhEUgAAALQAAAC0CAYAAAA9zQYyAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAABx0RVh0U29mdHdhcmUAQWRvYmUgRmlyZXdvcmtzIENTNui8sowAAAAVdEVYdENyZWF0aW9uIFRpbWUAMy8xNC8xM5HEXFoAAABhSURBVHja7cExAQAAAMKg9U9tDB+gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4GYABoQAAWd1bMQAAAAASUVORK5CYII=
EOF

base64 -d > icon-192.png << 'EOF'
iVBORw0KGgoAAAANSUhEUgAAAMAAAADACAYAAABS3GwHAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEwAACxMBAJqcGAAAABx0RVh0U29mdHdhcmUAQWRvYmUgRmlyZXdvcmtzIENTNui8sowAAAAVdEVYdENyZWF0aW9uIFRpbWUAMy8xNC8xM5HEXFoAAABhSURBVHja7cExAQAAAMKg9U9tCB+gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4GYABoQAAWd1bMQAAAAASUVORK5CYII=
EOF

base64 -d > icon-512.png << 'EOF'
iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAYAAAD0eNT6AAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAABx0RVh0U29mdHdhcmUAQWRvYmUgRmlyZXdvcmtzIENTNui8sowAAAAVdEVYdENyZWF0aW9uIFRpbWUAMy8xNC8xM5HEXFoAAABhSURBVHja7cExAQAAAMKg9U9tCB+gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4GYABoQAAWd1bMQAAAAASUVORK5CYII=
EOF

chmod +x create-icons.sh
echo "✅ Icon files created!"
ls -lh *.png 2>/dev/null || echo "No PNG files found"
